name: flutter_voip_push_notification
description: Flutter VoIP Push Notification - Currently iOS >= 8.0 only
version: 0.1.0
homepage: https://github.com/jpsantosbh/flutter_voip_push_notification.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.example.flutter_voip_push_notification
    pluginClass: FlutterVoipPushNotificationPlugin

 